### ISSUE TITLE
Uncaught TypeError: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by apaleslimghost** [arthur-xavier/atom-which-key#1]
Happens on literally every keypress.

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: [which-key](https://github.com/arthur-xavier/atom-which-key) package 0.3.2

### Stack Trace

Uncaught TypeError: Cannot read property 'constructor' of undefined

```
At /Users/matthew.brennan/.atom/packages/which-key/lib/which-key.js:50

TypeError: Cannot read property 'constructor' of undefined
    at WhichKey.match (which-key.js:50:9)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/atom-keymap/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/atom-keymap/node_modules/event-kit/lib/emitter.js:125:28)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:404:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  2x -0:37.9.0 core:delete (input.hidden-input)
     -0:33.7.0 core:backspace (input.hidden-input)
     -0:07.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
immersive-nucleus-dark-ui 1.10.0 
isotope-ui 2.8.0 
makika-syntax 1.0.0 
no-title-bar 0.6.2 
nucleus-dark-ui 0.11.0 
proton 4.0.2 
which-key 0.3.2 
```

**Comment by arthurxavierx** [comment]
Hm, I believe there are two options for this error:

1. Maybe some sort of conflict with `proton`'s `proton-which-key`, or
2. Some API breaking change in Atom 1.16-beta0

Anyway, I've tested it with Atom 1.15 and couldn't reproduce this bug. I'll try and test against 1.16-beta soon and will investigate this further. Thanks for reporting! 👍

**Comment by apaleslimghost** [comment]
The `proton` in the list is the [theme](https://atom.io/themes/proton), not proton-mode 😄 

Sounds like this is a 1.16 problem, thanks for looking into it

**Comment by apaleslimghost** [comment]
Had a look myself. It looks like `which-key-view.js` isn't properly exporting `Partial`, `Failed`, and `Nothing`, so in `which-key.js` they're `undefined`. I have no idea why this isn't working though.

**Comment by arthurxavierx** [comment]
Hm, it seems that Babel implemented the spec for exporting variables incorrectly as you've said in atom/atom#13823. I'll accept the PR and update the package in a few hours, as soon as I get home today. Thanks for the help! :)
